apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-gist-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-gist-api
  template:
    metadata:
      labels:
        app: flask-gist-api
    spec:
      containers:
        - name: flask-gist-api
          image: flask-gist-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: FLASK_ENV
              value: production
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: flask-gist-api
spec:
  selector:
    app: flask-gist-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
