apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-gist-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: flask-gist-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: "redis-service"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
spec:
  selector:
    app: flask-api
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # You can change this or let it auto-assign
