name: Deploy to Local Minikube

on:
  push:
    branches: [main]

jobs:
  deploy:
    if: false
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start Minikube
        run: |
          minikube start --driver=docker
          minikube status

      - name: Show Kubernetes nodes
        run: kubectl get nodes

      - name: Use Docker environment of Minikube
        run: |
          minikube docker-env --shell powershell | Invoke-Expression
          docker build -t flask-gist-api:latest .

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/redis-deployment.yaml
          kubectl apply -f k8s/flask-deployment.yaml

      - name: Wait for Deployment
        run: |
          kubectl rollout status deployment/flask-gist-api --timeout=90s

      # - name: Port forward and run tests
      #   shell: powershell
      #   run: |
      #     Start-Job { kubectl port-forward svc/flask-gist-api 8080:80 }
      #     Start-Sleep -Seconds 60
      #     # Run your test that hits http://localhost:8080
      #     curl http://localhost:8080/healthz
      #     Get-Job | Stop-Job